config/routes.rb
Rails.application.routes.draw do
  resources :donations
  resources :charges

  root :to => 'donations#index'

end

app/models/charges.rb
class Charges < ActiveRecord::Base

  has_one :donation

  def self.levels_for_dropdown
    donation_levels = Donation.all.collect do |donation|
      ["#{donation.level} - $#{donation.price}", donation.id]
    end
  end

  def self.total_donations
    @all_charges = Stripe::Charge.all
    total_amount = 0
    @donations_array = @all_charges.map do |thing|
      total_amount += thing['amount']
    end
    @total_donations = total_amount/100
  end

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  has_many :charges

  def self.days_left
    start_date = DateTime.now
    end_date = DateTime.parse "2014-11-07 00:00:00 +0500"
    (end_date - start_date).to_i
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @charge = Charges.new
  end

  def create
    # Amount in cents
    @amount = Donation.find(params[:charges][:donation_id])

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount.price * 100,
      :description => 'RubyConf Sponsorship',
      :currency    => 'usd'
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show]

  def index
    @donations = Donation.all
    @charge = Charges.new
  end


  def show
  end

  def create
    @donation = Donation.new(donation_params)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:level, :price, :level_descrip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/charges/create.html.erb
<div class="part_one">
  <h2>Thanks, you paid <strong>$<%= @amount.price %>.00</strong>!</h2>
  <h3>Your support is greatly appreciated! I will email you for any information I might need (mailing address, photograph, etc.) at some point before RubyConf.</h3>
  <h3>Please contact liz@lizbaillie.com if you have any questions or concerns.</h3>
  <%= link_to 'Return to the main page', root_path %>
</div>

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :level_descrip %><br>
    <%= f.text_field :level_descrip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<div class="top">
  <h1>Send Liz to RubyConf!</h1>
  <%= image_tag('me_with_dogs.jpg') %><br>
  <h2>$<%= Charges.total_donations %> / $1000 raised</h2>
  <h2> <%= Donation.days_left %> days left </h2>
</div>

<div class="part_one">
  <div class="title_font">
    <h2>My name is Liz, and I'm a RubyConf 2014 Opportunity Scholar!</h2>
  </div>
  <p>
    This is great news! I would never have been able to afford the $400 entry fee on my own. However, the scholarship does not cover air fare or accomodations, so I'm crowdfunding the rest by building this site (in Ruby, of course) and reaching out to the community.
    
    In my previous life, I was a published cartoonist and illustrator with <a href="http://www.amazon.com/Liz-Baillie/e/B00JBZPCLM/ref=sr_tc_2_0?qid=1413508895&sr=1-2-ent">several books</a> and a <a href="http://www.freewheelcomics.com">webcomic</a> under my belt (I even have a bachelor's degree in comics and a <a href="http://en.wikipedia.org/wiki/Liz_Baillie">Wikipedia page</a>). After hitting some hard times, I went back to school to explore a more stable career path. I always loved science and math, and ended up stumbling upon a CompSci 101 class where I absolutely fell in love with programming!<br><br>

    Shortly after, I discovered the <a href="http://www.flatironschool.com">Flatiron School</a> here in NYC and spent the entirety of this past summer using nearly every waking hour I had to study web development (specifically, Ruby and Rails with just a touch of JavaScript). I graduated at the end of August and have since spent most of my time going on job interviews, working on <a href="http://www.github.com/lizzerdrix">side projects</a>, going over tutorials, and networking at meetups. <br><br>

    <b>I'm doing everything I can to obtain a full-time developer position, but I'm not there yet. I know that attending RubyConf as an Opportunity Scholar will push me substantially closer to that goal. </b>
  </p>
  <div class="how_to_help">
    <h4>There are three ways you can help:</h4>
    <ul>
      <li>Choose a sponsorship level below to help me directly</li>
      <li>Share this page with your friends</li>
      <li><b><a href="http://www.lizbaillie.com/resume2014.pdf">Hire me</a></b>! I'm looking for a junior dev position. <b>If I can secure a job before RubyConf, <i>I will refund every dollar I was given</i>.</b> And what's more is, I'll still make good on all my pledge promises!</li>
    </ul>
  </div>
</div>

<div class="part_two">
  <h1>Sponsorship Levels</h1><br>
<% @donations.each do |donation| %>
  <p>
    <b><%= donation.level %><br><br></b>
    Price: $<%= donation.price %><br>
    <%= donation.level_descrip %><br>
  </p>
<% end %>

<%= form_for @charge, url: charges_path do |f| %>
  <%= f.select(:donation_id, Charges.levels_for_dropdown) %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="RubyConf Sponsorship"
          data-amount="<%= @amount %>"></script>
<% end %>

</div>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @donation.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donation.email %>
</p>

<p>
  <strong>Level:</strong>
  <%= @donation.level %>
</p>

<p>
  <strong>Price:</strong>
  <%= @donation.price %>
</p>

<p>
  <strong>Level descrip:</strong>
  <%= @donation.level_descrip %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/items/index.html.erb
<div class="top">
  <h1>Send Liz to RubyConf!</h1>
  <%= image_tag('me_with_dogs.jpg') %>
</div>

<div class="part_one">
  <div class="title_font">
    <h2>My name is Liz, and I'm a RubyConf 2014 Opportunity Scholar!</h2>
  </div>

    <h3>This is great news! I would never have been able to afford the $400 entry fee on my own. However, the scholarship does not cover air fare or accomodations, so I'm crowdfunding the rest by building this site (in Ruby, of course) and reaching out to the community.</h3>
</div>

<div class="part_two">
  <div class="title_font">
    <h2>
      About Me<br>
    </h2>
  </div>
    <p>
      In my previous life, I was a published cartoonist and illustrator with <a href="http://www.amazon.com/Liz-Baillie/e/B00JBZPCLM/ref=sr_tc_2_0?qid=1413508895&sr=1-2-ent">several books</a> and a <a href="http://www.freewheelcomics.com">webcomic</a> under my belt (I even have a bachelor's degree in comics and a <a href="http://en.wikipedia.org/wiki/Liz_Baillie">Wikipedia page</a>). After hitting some hard times, I went back to school to explore a more stable career path. I always loved science and math, and ended up stumbling upon a CompSci 101 class where I absolutely fell in love with programming!<br><br>

      Shortly after, I discovered the <a href="http://www.flatironschool.com">Flatiron School</a> here in NYC and spent the entirety of this past summer using nearly every waking hour I had to study web development (specifically, Ruby and Rails with just a touch of JavaScript). I graduated at the end of August and have since spent most of my time going on job interviews, working on <a href="http://www.github.com/lizzerdrix">side projects</a>, going over tutorials, and networking at meetups. <br><br>

      <b>I'm doing everything I can to obtain a full-time developer position, but I'm not there yet. I know that attending RubyConf as an Opportunity Scholar will push me substantially closer to that goal. </b>
    </p>
  <div class="how_to_help">
    <h4>There are three ways you can help:</h4>
    <ul>
      <li>Choose a sponsorship level below to help me directly</li>
      <li>Share this page with your friends</li>
      <li><b><a href="http://www.lizbaillie.com/resume2014.pdf">Hire me</a></b>! I'm looking for a junior dev position. <b>If I can secure a job before RubyConf, <i>I will refund every dollar I was given</i>.</b> And what's more is, I'll still make good on all my pledge promises!</li>
    </ul>
  </div>
</div>

<div class="part_three">
  <h1>Sponsorship Levels</h1>
<% @items.each do |item| %>
  <p>
    <b><%= item.item_name %><br></b>
    Price: $<%= item.item_price %><br>
    <%= item.item_descrip %><br>
  </p>
<% end %>

<%= render 'orders/form' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Send Liz to RubyConf!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
<footer>
  <br>
  &copy; Liz Baillie 2014 / Contact: liz@lizbaillie.com / <a href="http://www.lizbaillie.com" style="color: white;">Blog</a> / <a href="https://twitter.com/infinite_math" style="color: white;">Twitter</a> / <a href="https://github.com/lizzerdrix" style="color: white;">GitHub</a> / <a href="www.linkedin.com/pub/liz-baillie/62/619/b67/" style="color: white;">LinkedIn</a>
</footer>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Send Liz to RubyConf!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/orders/checkout.html.erb
<h1>You are sponsor number <%= @sponsors %>. Thank you for your patronage!</h1><br>
<h3><%= link_to "Return to the main page", root_path %></h3>